CODENAME_RULES = """
Codenames is a team-based party game based on cluegiving with limited communication between a team's spymaster and his fellow agents.

Players will be divided into Red Team and Blue Team. At the start of each round, each team will select a team leader, or spymaster. The two spymasters will be told secret information about a grid of words, which they will need to convey using limited clues to their teammates. The team leaders will take turns giving clues and taking guesses from their teammates. Once all of one team's words have been guessed, that team wins the round. The spymaster changes from round to round. The first team to win two rounds wins!

Setup:

A 5x5 grid of 25 words (codenames) will be generated by the Moderator and given to the players, as seen below.
WIND    FAITH   HOSPITAL    JOY TEAR
GUN	GLOVE	TRAFFIC	SUIT	DRESS
EAR	STOOL	BEARD	LEG	VACUUM
AMERICA	HORSE	TEAM	TATTOO	EXCUSE
NIGHT	CLIFF	LACE	COUCH	MILLIONAIRE

Each word will have a color assigned to it in secret that only the Moderator and the Team leaders will be able to see. I will randomly assign colors to the 25 word as follows: 8-9 Blue, 8-9 Red, 7 Grey, 1 Black (team that goes first has one extra word to guess). I will PM both spymasters the assignment of each word to its color, so that they know which word belong to their teams, but the other team members do not (All the other players know are the 25 words in the grid).

Here is an example of the above grid with colors assigned and Red as the starting team, that would be sent to the team spymasters:
WIND	FAITH	HOSPITAL	JOY	TEAR
GUN	GLOVE	TRAFFIC	SUIT	DRESS
EAR	STOOL	BEARD	LEG	VACUUM
AMERICA	HORSE	TEAM	TATTOO	EXCUSE
NIGHT	CLIFF	LACE	COUCH	MILLIONAIRE

Gameplay:

Each team's turn is broken up into two steps: giving a clue, and pointing at words.

Giving a Clue: The spymaster will post a clue to get teammates to guess a word or words of their color. He does so by giving both a one-word clue that is related to one or more of the words in the grid, and a number which tells his teammates how many words are related to that clue. For instance, he might say "Delay 3." That means that there are three words that are related to the word "Delay". He can say ONLY those two things: one word and one number. They must bold this to make it clear that is their official clue. After that, they are done posting for that turn.

The spymaster may give a clue as above, but offer no further commentary while a round is ongoing. If you are a spymaster, take care to review the typical-ish rules for giving clues in word guessing games listed below.

0. No using Google or Wikipedia, etc, for making or guessing clues. You would get chided at a table for pulling out your phone to look up a word during a game, so don't do it online either.
1. Your clue must be about the meaning of the words.
(e.g. You can't use your clue to talk about the letters in a word or its position on the table. GLAND is NOT a valid clue for ENGLAND. You can't tie BED, BUG, and BOW together with a clue of "B 3".)
2. Letters and numbers are valid clues as long as they refer to meanings.
(e.g. EIGHT 2 is a valid clue for SPIDER and FIGURE.)
3. The number you say after your clue can't be used as a clue.
(e.g. CITRUS 8 is not a valid clue for LEMON and OCTOPUS.)
4. You must play in English. A foreign word is allowed only if it can be reasonably used in an English sentence.
5. You can't use any form of a word that has not yet been identified on the grid.
(e.g. Until BREAK has been guessed, you cannot say BREAK, BROKEN, BREAKDOWN, etc.)
6. You cannot say part of a compound word that has not yet been identified.
(e.g. If HORSESHOE is in play, you cannot say HORSE, SHOE, UNHORSED, SNOWSHOE, etc.)
7. Rhymes are only valid when they refer to the meaning of the word.
(SNAIL is a valid clue for MAIL, but it is not a valid clue for SCALE.)
8. Proper names are allowed, if they follow the One Word rule.
(EINSTEIN is a valid clue, but ALBERT EINSTEIN is not).
9. Acronyms are not allowed, unless an acronym is primarily used as a regular word.
(RADAR is a valid clue, but CIA or USSR is not).  

Pointing at Words: Now the rest of team must select words to guess at, one at a time. Players must bold this pointing action to make it official (eg, "Point to America"). They can guess up to a max of one more word than the number stated by the spymaster (To try to catch up from missing past clues, see below).

Once they point to a word, the moderator or one of the spymasters reveals the color of that word. If the word is the color of the guessing team, the team may continue guessing words (up to the number given in the clue + 1). If the color of the word is either Grey, or the other team's color, the turn immediately ends and the other team takes a turn (Though players can try to guess any words they had missed on a later turn).

If the color is Black (Assassin) then the round immediately ends and the other team wins the round.

The team must make at least one guess; after this, the team may stop at any time by posting the word "Pass" in bold in the thread.

Any player on a team can make a guess, unless the team decides at any point to use a different system (one official guesser, vote for guess, etc).

Win Condition: The first team to have all 8 or 9 of their words revealed (by either team) wins the round. If this is that team's first winning round, the starting team switches and another round is played. If this is that team's second winning round, that team wins the game.
"""